dic = {}
name = input("Enter the name: ")
lang = input("Enter the language: ")
dic.update({name:lang})
name = input("Enter the name: ")
lang = input("Enter the language: ")
dic.update({name:lang})
name = input("Enter the name: ")
lang = input("Enter the language: ")
dic.update({name:lang})
name = input("Enter the name: ")
lang = input("Enter the language: ")
dic.update({name:lang})
print(dic)